### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by sirn524** [aiorhiroki/farmer#60]
File "<string>", line 63, in __init__
 File "/usr/local/lib/python3.6/dist-packages/farmer/domain/model/trainer_model.py", line 63, in __post_init__
  self.val_dirs = [str(val_dir) for val_dir in self.val_dirs]

以下のyaml file読み込み時にエラーが発生しています。

target_dir: data/IMA
result_root_dir: result
train_dirs:
test_dirs:
val_dirs:
training: yes
task: segmentation # classification or segmentation is supported
model_name: deeplab_v3
backbone: mobilenetv2
loss: dice_loss
epochs: 100
batch_size: 8
optimizer: adam
learning_rate: 0.01
width: 512
height: 256
input_dir: movieframe
label_dir: label
trained_model_path: 
result_dir: IMA
class_names:
train_colors:

**Comment by aiorhiroki** [comment]
soloved !
https://github.com/aiorhiroki/farmer/blob/c0c44805e73c43cc8e8f744f35224169652d788b/farmer/domain/model/trainer_model.py#L66
